apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    application: coolstore
    component: coolstore-gw
  name: coolstore-gw
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    deploymentconfig: coolstore-gw
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        application: coolstore
        component: coolstore-gw
        deploymentconfig: coolstore-gw
      name: coolstore-gw
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{REGISTRY}}/coolstore-dev/coolstore-gw:@APP_VERSION@
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
        name: coolstore-gw
        ports:
        - containerPort: 8778
          name: jolokia
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 512Mi
  triggers:
  - type: ConfigChange
