apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    application: coolstore
    component: catalog
  name: catalog-postgresql
spec:
  replicas: 1
  selector:
    deploymentconfig: catalog-postgresql
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: coolstore
        component: catalog
        deploymentconfig: catalog-postgresql
      name: catalog-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: {{CATALOG_DB_USERNAME}}
        - name: POSTGRESQL_PASSWORD
          value: {{CATALOG_DB_PASSWORD}}
        - name: POSTGRESQL_DATABASE
          value: catalogdb
        image: {{REGISTRY}}/openshift/postgresql:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 1
        name: catalog-postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
              'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - catalog-postgresql
      from:
        kind: ImageStreamTag
        name: postgresql:latest
        namespace: openshift
    type: ImageChange
  - type: ConfigChange
