apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    application: coolstore
    component: catalog
  name: catalog
spec:
  replicas: 1
  selector:
    deploymentconfig: catalog
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        application: coolstore
        component: catalog
        deploymentconfig: catalog
      name: catalog
    spec:
      containers:
      - env:
        - name: JWS_ADMIN_USERNAME
          value: Skq3VtCd
        - name: JWS_ADMIN_PASSWORD
          value: oktt6yhw
        - name: DB_USERNAME
          value: {{CATALOG_DB_USERNAME}}
        - name: DB_PASSWORD
          value: {{CATALOG_DB_PASSWORD}}
        - name: DB_NAME
          value: catalogdb
        - name: DB_SERVER
          value: catalog-postgres
        image: {{REGISTRY}}/coolstore-dev/catalog:@APP_VERSION@
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 20
        name: catalog
        ports:
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 20
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /deployments/config
          name: config-catalog-m5y28
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 75
      volumes:
      - configMap:
          defaultMode: 420
          name: config-catalog
        name: config-catalog-m5y28
  test: false
  triggers:
  - type: ConfigChange

