apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    application: coolstore
    component: inventory
  name: inventory-postgresql
spec:
  replicas: 1
  selector:
    deploymentconfig: inventory-postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: coolstore
        component: inventory
        deploymentconfig: inventory-postgresql
      name: inventory-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: user
        - name: POSTGRESQL_PASSWORD
          value: password
        - name: POSTGRESQL_DATABASE
          value: inventorydb
          image: {{REGISTRY}}/openshift/postgresql:latest
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 5432
            timeoutSeconds: 1
          name: inventory-postgresql
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
                'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
        terminationGracePeriodSeconds: 60
  triggers:
  - type: ConfigChange
