apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    application: coolstore
    component: inventory
  name: inventory
spec:
  replicas: 1
  selector:
    deploymentconfig: inventory
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        application: coolstore
        component: inventory
        deploymentconfig: inventory
      name: inventory
    spec:
      containers:
      - env:
        - name: OPENSHIFT_KUBE_PING_LABELS
          value: application=inventory
        - name: OPENSHIFT_KUBE_PING_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MQ_CLUSTER_PASSWORD
          value: 7mzX0pLV03
        - name: JGROUPS_CLUSTER_PASSWORD
          value: CqUo3fYDTv
        - name: AUTO_DEPLOY_EXPLODED
          value: 'false'
        - name: DB_SERVICE_PREFIX_MAPPING
          value: inventory-postgresql=DB
        - name: DB_JNDI
          value: java:jboss/datasources/InventoryDS
        - name: DB_USERNAME
          value: user
        - name: DB_PASSWORD
          value: password
        - name: DB_DATABASE
          value: inventorydb
        image: {{REGISTRY}}/coolstore-dev/inventory:@APP_VERSION@
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /opt/eap/bin/jboss-cli.sh
              - -c
              - :shutdown(timeout=60)
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /node
            port: 8080
            scheme: HTTP
          initialDelaySeconds: {{inventory.initialDelaySeconds}}
          periodSeconds: {{inventory.periodSeconds}}
          successThreshold: 1
          timeoutSeconds: {{inventory.timeoutSeconds}}
        name: inventory
        ports:
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8888
          name: ping
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /node
            port: 8080
            scheme: HTTP
          initialDelaySeconds: {{inventory.initialDelaySeconds}}
          periodSeconds: {{inventory.periodSeconds}}
          successThreshold: 1
          timeoutSeconds: {{inventory.timeoutSeconds}}
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 75
  triggers:
  - type: ConfigChange
