apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    application: coolstore
    component: web-ui
  name: web-ui
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: web-ui
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        application: coolstore
        component: web-ui
        deploymentconfig: web-ui
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: COOLSTORE_GW_ENDPOINT
          value: gw-coolstore-{{env}}
        - name: HOSTNAME_HTTP
          value: web-ui:8080
        - name: ENVIRONMENT
          value: {{ENVIRONMENT}}
        - name: COMPONENT_VERSION
          value: v@APP_VERSION@
        - name: ENVIRONMENT_COLOR
          value: {{ENVIRONMENT_COLOR}}
        image: {{REGISTRY}}/coolstore-dev/web-ui:@APP_VERSION@
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: web-ui
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - web-ui
      from:
        kind: ImageStreamTag
        name: web-ui:latest
        namespace: coolstore-dev
    type: ImageChange
  - type: ConfigChange

